modLoader="javafml"
loaderVersion="[2,)"
license="All rights reserved"

[[mods]]
modId="arcaneitems"
version="1.0.0"
displayName="Arcane Items"
authors="Thiago"
description='''Arcane Items é um mod que adiciona itens mágicos ao jogo, incluindo o Dash Wand com habilidades únicas.'''

[[dependencies.arcaneitems]]
modId="neoforge"
type="required"
versionRange="[2,)"
ordering="NONE"
side="BOTH"

[[dependencies.arcaneitems]]
modId="minecraft"
type="required"
versionRange="[1.16,2)"
ordering="NONE"
side="BOTH"

[mixin]
config="arcaneitems.mixins.json"
